[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Advent of Code 2024"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "jinja2>=3.1.4",
    "pytest>=8.3.4",
]

